name: Compile and Package hardducky

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y devscripts debhelper dh-python python3-all

      - name: Prepare the debian directory
        run: |
          mkdir -p package/hardducky/DEBIAN
          cp hardducky/DEBIAN/control package/hardducky/DEBIAN/
          cp hardducky/DEBIAN/postinst package/hardducky/DEBIAN/
          chmod +x package/hardducky/DEBIAN/postinst

      - name: Copy application files
        run: |
          mkdir -p package/hardducky/etc/hardducky/
          cp hardducky/etc/hardducky/hardducky.conf package/hardducky/etc/hardducky/
          mkdir -p package/hardducky/lib/systemd/system/
          cp hardducky/lib/systemd/system/hardducky.service package/hardducky/lib/systemd/system/
          mkdir -p package/hardducky/usr/bin/
          cp hardducky/usr/bin/hardducky package/hardducky/usr/bin/
          cp hardducky/usr/bin/hardducky-tools package/hardducky/usr/bin/
          chmod +x package/hardducky/usr/bin/hardducky
          chmod +x package/hardducky/usr/bin/hardducky-tools

      - name: Build the .deb package
        run: |
          dpkg-deb --build package/hardducky package/hardducky.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hardducky-deb
          path: package/hardducky.deb

      - name: Create GitHub Release (on tag)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: package/hardducky.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
